### ISSUE TITLE
CH4 - Determine how to tag images with a build number

### ISSUE THREAD

**Issue by clarenceb** [clarenceb/openhack-devops-team#23]

**Comment by clarenceb** [comment]
Building an image and publishing to GitHub Packages can be done like so:

```
build-and-push-image:
    runs-on: ubuntu-latest
    needs: run-npm-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/octo-image
        tag_with_sha: true
        tag_with_ref: true
```

The image can be tagged with the git SHA (first 7 chars), git ref (e.g. branch name or tag) or using the workflow number/ID:

`github.run_id` - A unique number for each run within a repository. This number does not change if you re-run the workflow run.

`github.run_number` -  A unique number for each run of a particular workflow in a repository. This number begins at 1 for the workflow's first run, and increments with each new run. This number does not change if you re-run the workflow run.

References:

* https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions
* https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
